### ISSUE TITLE
Shaking when stationary

### ISSUE THREAD

**Issue by VoladorUK** [slawekmikula/flightgear-addon-fgcamera#18]
Brilliant addon! Similar to Beni's request, could the shaking be dependant on speed? For example little to no shaking when stationary.

**Comment by slawekmikula** [comment]
Thanks, but all of the work was done by MariusA. This repository is a bit behind the fork by PlayeRom and he has taken all of the development. I suggest raising this issue in that repository (https://github.com/PlayeRom/flightgear-addon-fgcamera). PlayeRom's repository is mentioned in the readme. I'll close this issue here. I hope this is understandable.
